#include "radiotools.h"
namespace radioTools {
HMODULE hAPI = LoadLibrary(L"g35ddcapi.dll");
//common
//COH_G35DDC_GET_DEVICE_SET_LIST CohGetDeviceSetList=(COH_G35DDC_GET_DEVICE_SET_LIST)GetProcAddress(hAPI,"CohGetDeviceSetList");
//COH_G35DDC_FREE_DEVICE_SET_LIST CohFreeDeviceSetList=(COH_G35DDC_FREE_DEVICE_SET_LIST)GetProcAddress(hAPI,"CohFreeDeviceSetList");
//COH_G35DDC_OPEN_DEVICE_SET CohOpenDeviceSet=(COH_G35DDC_OPEN_DEVICE_SET)GetProcAddress(hAPI,"CohOpenDeviceSet");
//COH_G35DDC_CLOSE_DEVICE_SET CohCloseDeviceSet=(COH_G35DDC_CLOSE_DEVICE_SET)GetProcAddress(hAPI,"CohCloseDeviceSet");
//COH_G35DDC_IS_CONNECTED CohIsConnected=(COH_G35DDC_IS_CONNECTED)GetProcAddress(hAPI,"CohIsConnected");
//COH_G35DDC_GET_DEVICE_COUNT CohGetDeviceCount=(COH_G35DDC_GET_DEVICE_COUNT)GetProcAddress(hAPI,"CohGetDeviceCount");
//COH_G35DDC_GET_DEVICE_INFO CohGetDeviceInfo=(COH_G35DDC_GET_DEVICE_INFO)GetProcAddress(hAPI,"CohGetDeviceInfo");
//COH_G35DDC_GET_DEVICE_INFOS CohGetDeviceInfos=(COH_G35DDC_GET_DEVICE_INFOS)GetProcAddress(hAPI,"CohGetDeviceInfos");
//COH_G35DDC_SET_POWER CohSetPower=(COH_G35DDC_SET_POWER)GetProcAddress(hAPI,"CohSetPower");
//COH_G35DDC_GET_POWER CohGetPower=(COH_G35DDC_GET_POWER)GetProcAddress(hAPI,"CohGetPower");
// DDC1
//COH_G35DDC_GET_DDC_INFO CohGetDDCInfo=(COH_G35DDC_GET_DDC_INFO)GetProcAddress(hAPI,"CohGetDDCInfo");
//COH_G35DDC_GET_DDC1_COUNT CohGetDDC1Count=(COH_G35DDC_GET_DDC1_COUNT)GetProcAddress(hAPI,"CohGetDDC1Count");
//COH_G35DDC_SET_DDC1 CohSetDDC1=(COH_G35DDC_SET_DDC1)GetProcAddress(hAPI,"CohSetDDC1");
//COH_G35DDC_GET_DDC1 CohGetDDC1=(COH_G35DDC_GET_DDC1)GetProcAddress(hAPI,"CohGetDDC1");
//COH_G35DDC_SET_DDC1_FREQUENCY CohSetDDC1Frequency=(COH_G35DDC_SET_DDC1_FREQUENCY)GetProcAddress(hAPI,"CohSetDDC1Frequency");
//COH_G35DDC_GET_DDC1_FREQUENCY CohGetDDC1Frequency=(COH_G35DDC_GET_DDC1_FREQUENCY)GetProcAddress(hAPI,"CohGetDDC1Frequency");
//COH_G35DDC_SET_DDC1_PHASE_SHIFT CohSetDDC1PhaseShift=(COH_G35DDC_SET_DDC1_PHASE_SHIFT)GetProcAddress(hAPI,"CohSetDDC1PhaseShift");
//COH_G35DDC_GET_DDC1_PHASE_SHIFT CohGetDDC1PhaseShift=(COH_G35DDC_GET_DDC1_PHASE_SHIFT)GetProcAddress(hAPI,"CohGetDDC1PhaseShift");
//COH_G35DDC_START_DDC1 CohStartDDC1=(COH_G35DDC_START_DDC1)GetProcAddress(hAPI,"CohStartDDC1");
//COH_G35DDC_STOP_DDC1 CohStopDDC1=(COH_G35DDC_STOP_DDC1)GetProcAddress(hAPI,"CohStopDDC1");
//callbacks
//COH_G35DDC_SET_CALLBACKS CohSetCallbacks=(COH_G35DDC_SET_CALLBACKS)GetProcAddress(hAPI,"CohSetCallbacks");
}
